# build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY Shop.sln ./
COPY src ./src

RUN dotnet restore "src/OrderService/OrderService.csproj"
RUN dotnet publish "src/OrderService/OrderService.csproj" -c Release -o /app/publish

# runtime
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet","OrderService.dll"]
